name: {{cookiecutter.project_name.lower().replace(' ', '_')}}_docs
 dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   - numpy
   - xarray
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - pip:
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks